### ISSUE TITLE
TypeError: Cannot read property 'alloc' of undefined

### ISSUE THREAD

**Issue by bcaller** [jacobrask/node-upnp-device#11]
I tried to run the examples/test.js file to check whether this works and I get:

```
$ node examples/test.js
Web server listening on http://192.168.1.7:50793
c:\...\node-upnp-device\lib\devices\Device.coffee:145
      parser = http.parsers.alloc();
                           ^
TypeError: Cannot read property 'alloc' of undefined
    at MyDevice.Device.parseRequest (c:\...\node-upnp-device\lib\devices\Device.coffee:145:28)
    at MyDevice.Device.ssdpListener (c:\...\node-upnp-device\lib\devices\Device.coffee:375:19)
    at Socket.<anonymous> (c:\...\node-upnp-device\lib\devices\Device.coffee:6:63)
    at Socket.emit (events.js:110:17)
    at UDP.onMessage (dgram.js:472:8)
```

**Comment by bcaller** [comment]
I think I've fixed it with

```
    HTTPParser = process.binding('http_parser').HTTPParser;
    parser = new HTTPParser 'request'
```

**Comment by eelcocramer** [comment]
Thanks for the fixed. I've pushed a new version to npm.
